#!/usr/bin/env bash
set -euo pipefail

# Simplified Android Build Script
# Since Dioxus 0.7, custom AndroidManifest.xml and MainActivity.kt are natively supported.
# This script only handles:
# 1) Running dx build
# 2) Copying res/xml resources (file_paths.xml for FileProvider)
# 3) APK signing (optional for release builds)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Determine build mode
RELEASE_FLAG=""
BUILD_TYPE="debug"
if [[ "${1:-}" == "--release" ]]; then
    RELEASE_FLAG="--release"
    BUILD_TYPE="release"
fi

DX_APP_DIR="$ROOT_DIR/target/dx/stalltagebuch/$BUILD_TYPE/android/app"
APP_SRC_MAIN="$DX_APP_DIR/app/src/main"
RES_XML_DIR="$APP_SRC_MAIN/res/xml"

# 1) Dioxus Build
echo "[1/2] Running dx build --platform android $RELEASE_FLAG"
dx build --platform android $RELEASE_FLAG

# 2) Copy additional res/xml resources (required for FileProvider/Camera)
# Note: network_security_config.xml is auto-generated by Dioxus
echo "[2/2] Copying file_paths.xml for FileProvider"
mkdir -p "$RES_XML_DIR"
cp "$ROOT_DIR/android/res/xml/file_paths.xml" "$RES_XML_DIR/file_paths.xml"

# Output paths
if [[ "$BUILD_TYPE" == "release" ]]; then
    APK_PATH="$DX_APP_DIR/app/build/outputs/apk/release/app-release-unsigned.apk"
else
    APK_PATH="$DX_APP_DIR/app/build/outputs/apk/debug/app-debug.apk"
fi

echo ""
echo "✓ Android build completed"
echo "  APK location: $APK_PATH"
echo ""
echo "Installation with:"
echo "  adb install -r $APK_PATH"
