#!/bin/bash
set -e

echo "========================================="
echo "Preparing custom Android files..."
echo "========================================="

# Source files in our repo
MAIN_SOURCE="./android/MainActivity.kt"
BUILD_CONFIG_SOURCE="./android/BuildConfig.kt"
MANIFEST_SOURCE="./android/AndroidManifest.xml"
FILE_PATHS_SOURCE="./android/res/xml/file_paths.xml"

# Check if dx has created the directory structure yet
if [ ! -d "./target/dx/stalltagebuch/debug/android/app/app/src/main/kotlin/dev/dioxus/main" ]; then
    echo "⚠ Dioxus directory structure doesn't exist yet."
    echo "Creating directory structure..."
    mkdir -p "./target/dx/stalltagebuch/debug/android/app/app/src/main/kotlin/dev/dioxus/main"
    mkdir -p "./target/dx/stalltagebuch/debug/android/app/app/src/main/res/xml"
fi

# Copy files to debug build
TARGET_DEBUG="./target/dx/stalltagebuch/debug/android/app/app/src/main/kotlin/dev/dioxus/main/MainActivity.kt"
BUILD_CONFIG_DEBUG="./target/dx/stalltagebuch/debug/android/app/app/src/main/kotlin/dev/dioxus/main/BuildConfig.kt"
MANIFEST_DEBUG="./target/dx/stalltagebuch/debug/android/app/app/src/main/AndroidManifest.xml"
FILE_PATHS_DEBUG="./target/dx/stalltagebuch/debug/android/app/app/src/main/res/xml/file_paths.xml"

echo "Copying MainActivity.kt to debug build..."
cp "$MAIN_SOURCE" "$TARGET_DEBUG"
echo "✓ MainActivity.kt copied to debug"

# BuildConfig.kt is now auto-generated by Gradle based on namespace
echo "✓ BuildConfig will be auto-generated by Gradle"

echo "Copying AndroidManifest.xml to debug build..."
mkdir -p "$(dirname "$MANIFEST_DEBUG")"
cp "$MANIFEST_SOURCE" "$MANIFEST_DEBUG"
echo "✓ AndroidManifest.xml copied to debug"

echo "Copying file_paths.xml to debug build..."
mkdir -p "$(dirname "$FILE_PATHS_DEBUG")"
cp "$FILE_PATHS_SOURCE" "$FILE_PATHS_DEBUG"
echo "✓ file_paths.xml copied to debug"

echo "Copying network_security_config.xml to debug build..."
NETWORK_CONFIG_SOURCE="./android/res/xml/network_security_config.xml"
NETWORK_CONFIG_DEBUG="./target/dx/stalltagebuch/debug/android/app/app/src/main/res/xml/network_security_config.xml"
mkdir -p "$(dirname "$NETWORK_CONFIG_DEBUG")"
cp "$NETWORK_CONFIG_SOURCE" "$NETWORK_CONFIG_DEBUG"
echo "✓ network_security_config.xml copied to debug"

# Patch build.gradle.kts to use correct package name and SDK versions
GRADLE_FILE_DEBUG="./target/dx/stalltagebuch/debug/android/app/app/build.gradle.kts"
if [ -f "$GRADLE_FILE_DEBUG" ]; then
    echo "Patching build.gradle.kts for debug build..."
    sed -i 's/namespace="com\.example\.Stalltagebuch"/namespace="de.teilgedanken.stalltagebuch"/g' "$GRADLE_FILE_DEBUG"
    sed -i 's/applicationId = "com\.example\.Stalltagebuch"/applicationId = "de.teilgedanken.stalltagebuch"/g' "$GRADLE_FILE_DEBUG"
    sed -i 's/compileSdk = 33/compileSdk = 34/g' "$GRADLE_FILE_DEBUG"
    sed -i 's/targetSdk = 33/targetSdk = 34/g' "$GRADLE_FILE_DEBUG"
    sed -i 's/minSdk = 24/minSdk = 28/g' "$GRADLE_FILE_DEBUG"
    echo "✓ build.gradle.kts patched for debug"
fi

# Also copy to release build if it exists
if [ -d "./target/dx/stalltagebuch/release/android/app/app/src/main/kotlin/dev/dioxus/main" ]; then
    TARGET_RELEASE="./target/dx/stalltagebuch/release/android/app/app/src/main/kotlin/dev/dioxus/main/MainActivity.kt"
    BUILD_CONFIG_RELEASE="./target/dx/stalltagebuch/release/android/app/app/src/main/kotlin/dev/dioxus/main/BuildConfig.kt"
    MANIFEST_RELEASE="./target/dx/stalltagebuch/release/android/app/app/src/main/AndroidManifest.xml"
    FILE_PATHS_RELEASE="./target/dx/stalltagebuch/release/android/app/app/src/main/res/xml/file_paths.xml"
    
    echo "Copying MainActivity.kt to release build..."
    cp "$MAIN_SOURCE" "$TARGET_RELEASE"
    echo "✓ MainActivity.kt copied to release"
    
    # BuildConfig.kt is auto-generated
    echo "✓ BuildConfig will be auto-generated for release"
    
    echo "Copying AndroidManifest.xml to release build..."
    mkdir -p "$(dirname "$MANIFEST_RELEASE")"
    cp "$MANIFEST_SOURCE" "$MANIFEST_RELEASE"
    echo "✓ AndroidManifest.xml copied to release"
    
    echo "Copying file_paths.xml to release build..."
    mkdir -p "$(dirname "$FILE_PATHS_RELEASE")"
    cp "$FILE_PATHS_SOURCE" "$FILE_PATHS_RELEASE"
    echo "✓ file_paths.xml copied to release"
    
    echo "Copying network_security_config.xml to release build..."
    NETWORK_CONFIG_RELEASE="./target/dx/stalltagebuch/release/android/app/app/src/main/res/xml/network_security_config.xml"
    mkdir -p "$(dirname "$NETWORK_CONFIG_RELEASE")"
    cp "$NETWORK_CONFIG_SOURCE" "$NETWORK_CONFIG_RELEASE"
    echo "✓ network_security_config.xml copied to release"
    
    # Patch build.gradle.kts for release
    GRADLE_FILE_RELEASE="./target/dx/stalltagebuch/release/android/app/app/build.gradle.kts"
    if [ -f "$GRADLE_FILE_RELEASE" ]; then
        echo "Patching build.gradle.kts for release build..."
        sed -i 's/namespace="com\.example\.Stalltagebuch"/namespace="de.teilgedanken.stalltagebuch"/g' "$GRADLE_FILE_RELEASE"
        sed -i 's/applicationId = "com\.example\.Stalltagebuch"/applicationId = "de.teilgedanken.stalltagebuch"/g' "$GRADLE_FILE_RELEASE"
        sed -i 's/compileSdk = 33/compileSdk = 34/g' "$GRADLE_FILE_RELEASE"
        sed -i 's/targetSdk = 33/targetSdk = 34/g' "$GRADLE_FILE_RELEASE"
        sed -i 's/minSdk = 24/minSdk = 28/g' "$GRADLE_FILE_RELEASE"
        echo "✓ build.gradle.kts patched for release"
    fi
fi

echo "========================================="
echo "✓ All files prepared successfully"
echo "Now run: dx build --platform android"
echo "========================================="
